apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: giropops-servicemonitor
  name: giropops-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: giropops-service
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    path: /metrics
    interval: 30s


    