apiVersion: autoscaling/v2  
kind: HorizontalPodAutoscaler  
metadata:
  name: giropops-hpa  
spec:
  scaleTargetRef:
    apiVersion: apps/v1        
    kind: Deployment           
    name: giropops-deployment     
  minReplicas: 2               
  maxReplicas: 5              
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85