apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-deployment
  labels:
    app: giropops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giropops-senhas
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
      - name: giropops-senhas
        image: filipez/giropops-senhas:1.0
        env:
          - name: REDIS_HOST
            value: redis-headless-service
        ports:
        - containerPort: 5000
          name: http
        resources:
          requests:
            memory: "50Mi"
            cpu: 300m
          limits:
            memory: "80Mi"  
            cpu: 300m
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 5