apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  labels:
    app: redis-statefulset
spec:
  serviceName: redis-headless-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:  
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ['sh', '-c', 'chown -R 65532:65532 /data']
        volumeMounts:
        - name: redis-storage
          mountPath: /data

      containers:
      - name: redis
        image: cgr.dev/chainguard/redis
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 6379
          name: http
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      - name: redis-exporter
        image: oliver006/redis_exporter
        ports:
        - containerPort: 9121
          name: exporter-port
        env:
        - name: REDIS_ADDR
          value: localhost:6379
      volumes:
      - name: redis-storage
        emptyDir: {}
