name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: false
        tags: filipez/giropops-senhas:latest

    - name: Scan Docker image for vulnerabilities
      id: trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'filipez/giropops-senhas:latest'
        fail-on-severity: 'CRITICAL'

    - name: Build and push Docker image
      if: steps.trivy.outcome == 'success'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: filipez/giropops-senhas:latest


